logging:
  level:
    org.springframework: ERROR
    org.hibernate: ERROR
    com.moneysupermarket: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080
  servlet:
    contextPath: /exchangeapp

blockchain:
  url: https://blockchain.info

exmo:
  url: https://api.exmo.com/v1

bitfinex:
  url: https://api.bitfinex.com/v1